"""
import_gear.py
guild_equipment_*.json → GearImport.lua 변환기

사용법:
  python3 import_gear.py           # 최근 JSON 자동 선택
  python3 import_gear.py <파일명>  # 파일 지정

WoW 실행 중에도 사용 가능. 이후 /reload 하면 자동 반영.
"""

import json
import os
import glob
import sys
import time
import requests
from datetime import datetime

CLIENT_ID = "YOUR_CLIENT_ID"
CLIENT_SECRET = "YOUR_CLIENT_SECRET"
TOKEN_URL = "https://kr.battle.net/oauth/token"
API_BASE = "https://kr.api.blizzard.com"
STATIC_NS = "static-classicann-kr"

ADDON_DIR = os.path.dirname(os.path.abspath(__file__))
GEAR_IMPORT_LUA = os.path.join(ADDON_DIR, "GearImport.lua")
ITEM_CACHE_FILE = os.path.join(ADDON_DIR, "item_cache.json")

SLOT_MAP = {
    "HEAD": 1, "NECK": 2, "SHOULDER": 3, "CHEST": 5,
    "WAIST": 6, "LEGS": 7, "FEET": 8, "WRIST": 9,
    "HANDS": 10, "FINGER_1": 11, "FINGER_2": 12,
    "TRINKET_1": 13, "TRINKET_2": 14, "BACK": 15,
    "MAIN_HAND": 16, "OFF_HAND": 17, "RANGED": 18,
}

QUALITY_MAP = {
    "POOR": 0, "COMMON": 1, "UNCOMMON": 2, "RARE": 3,
    "EPIC": 4, "LEGENDARY": 5,
}

QUALITY_COLORS = {
    0: "9d9d9d", 1: "ffffff", 2: "1eff00", 3: "0070dd",
    4: "a335ee", 5: "ff8000",
}


def get_token():
    resp = requests.post(
        TOKEN_URL,
        data={"grant_type": "client_credentials"},
        auth=(CLIENT_ID, CLIENT_SECRET),
    )
    resp.raise_for_status()
    return resp.json()["access_token"]


def fetch_item_ilvl(token, item_id, cache):
    key = str(item_id)
    if key in cache:
        return cache[key]
    resp = requests.get(
        f"{API_BASE}/data/wow/item/{item_id}",
        params={"namespace": STATIC_NS},
        headers={"Authorization": f"Bearer {token}"},
    )
    ilvl = resp.json().get("level", 0) if resp.ok else 0
    cache[key] = ilvl
    time.sleep(0.05)
    return ilvl


def make_link(item_id, name, quality_num):
    color = QUALITY_COLORS.get(quality_num, "ffffff")
    return f"|cff{color}|Hitem:{item_id}::::::::70|h[{name}]|h|r"


def lua_str(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def build_lua(members, item_cache, fetched_at):
    ts = int(fetched_at)
    date_str = datetime.fromtimestamp(ts).strftime("%m/%d %H:%M")
    lines = [
        "-- Auto-generated by import_gear.py — do not edit manually",
        f"-- Generated: {datetime.fromtimestamp(ts).isoformat()}",
        "MyGreeting_ImportData = {",
        f'["fetched_at"] = {ts},',
        '["members"] = {',
    ]

    for name, member in members.items():
        item_lines = []
        total_ilvl, count = 0, 0

        for slot_type, slot_data in member["items"].items():
            slot_num = SLOT_MAP.get(slot_type)
            if slot_num is None:
                continue
            item_id = slot_data["id"]
            quality_num = QUALITY_MAP.get(slot_data.get("quality", ""), 1)
            ilvl = item_cache.get(str(item_id), 0)
            link = make_link(item_id, slot_data["name"], quality_num)

            item_lines.append(
                f'{{\n'
                f'["quality"] = {quality_num},\n'
                f'["link"] = {lua_str(link)},\n'
                f'["ilvl"] = {ilvl},\n'
                f'["slot"] = {slot_num},\n'
                f'}},'
            )
            if ilvl > 0:
                total_ilvl += ilvl
                count += 1

        avg_ilvl = (total_ilvl // count) if count > 0 else 0

        lines.append(f'[{lua_str(name)}] = {{')
        lines.append(f'["class"] = {lua_str(member.get("class", ""))},')
        lines.append(f'["ilvl"] = {avg_ilvl},')
        lines.append(f'["date"] = {lua_str(date_str)},')
        lines.append('["items"] = {')
        lines.extend(item_lines)
        lines.append('},')
        lines.append('},')

    lines.append('},')
    lines.append('}')
    return "\n".join(lines)


def main():
    # JSON 파일 선택
    if len(sys.argv) > 1:
        json_file = sys.argv[1]
    else:
        files = sorted(glob.glob(os.path.join(ADDON_DIR, "guild_equipment_*.json")), reverse=True)
        if not files:
            print("guild_equipment_*.json 없음. 먼저 get_guild_equipment.py를 실행하세요.")
            sys.exit(1)
        json_file = files[0]

    print(f"입력: {os.path.basename(json_file)}")
    with open(json_file, encoding="utf-8") as f:
        data = json.load(f)
    members = data["members"]
    fetched_at = datetime.fromisoformat(data["fetched_at"]).timestamp()
    print(f"멤버: {len(members)}명")

    # 아이템 캐시
    if os.path.exists(ITEM_CACHE_FILE):
        with open(ITEM_CACHE_FILE, encoding="utf-8") as f:
            item_cache = json.load(f)
        print(f"아이템 캐시: {len(item_cache)}개")
    else:
        item_cache = {}

    # 미캐시 아이템 ilvl 조회
    all_ids = {str(s["id"]) for m in members.values() for s in m["items"].values()}
    missing = [id for id in all_ids if id not in item_cache]

    if missing:
        print(f"ilvl 조회: {len(missing)}개 ... ", end="", flush=True)
        token = get_token()
        for item_id in missing:
            fetch_item_ilvl(token, item_id, item_cache)
        with open(ITEM_CACHE_FILE, "w", encoding="utf-8") as f:
            json.dump(item_cache, f, ensure_ascii=False)
        print("완료")

    # GearImport.lua 생성
    print("GearImport.lua 생성 중...", end="", flush=True)
    lua_content = build_lua(members, item_cache, fetched_at)
    with open(GEAR_IMPORT_LUA, "w", encoding="utf-8") as f:
        f.write(lua_content)
    print(" 완료")
    print(f"→ WoW에서 /reload 하면 {len(members)}명 자동 임포트됩니다.")


if __name__ == "__main__":
    main()
